-keep class com.rev4n.unlimitedphotos.EntryPoint { public <methods>; }
-keepclassmembers class com.rev4n.unlimitedphotos.CustomKeyStoreSpi
-keepclassmembers class com.rev4n.unlimitedphotos.CustomPackageInfoCreator { public <init>(...); }
-keepclassmembers class com.rev4n.unlimitedphotos.CustomProvider